### ISSUE TITLE
DB 테이블 생성

### ISSUE THREAD

**Issue by Go-Jaecheol** [KNUHR/Server#4]
- [x] 설계한 ERD 바탕으로 DB 테이블 생성  

![image](https://user-images.githubusercontent.com/33208246/187620581-a1a5af0d-55ef-4d99-a254-e569d79fa3fd.png)

**Comment by Go-Jaecheol** [comment]
- ### 주요 테이블 정보

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/33208246/187909162-c42cd614-bcd8-49ac-9c6f-19b8dd2d44ac.png">

**Comment by Go-Jaecheol** [comment]
* ## ERD 및 주요 테이블 정보 수정  
- `MEETING` - `CHATROOM` -> **1:N** 연결  
- `meeting_status` 컬럼 추가  
- `chat_id` **BIGINT**로 변경

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/33208246/188101095-570387b9-7dbc-41ee-bdad-4e04d42a1911.png">


<img width="1280" alt="image" src="https://user-images.githubusercontent.com/33208246/188101223-49516bbd-2eb4-4dc7-aa90-afbf79427b46.png">

**Comment by SeongukBaek** [comment]
Good

**Comment by Go-Jaecheol** [comment]
* ## 테이블 정보 수정

* `APPLYS` -> `APPLIES` 테이블 명 수정  
* `chat_sender_id`, `chat_chatroom_id` **FK** 추가  
* `chatroom_meeting_id` **FK** 추가

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/33208246/188276020-906d33fa-b988-43d8-a007-b2d802fa3aa1.png">

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/33208246/188275863-00f80b73-43ca-41de-864f-7244eff251f4.png">

**Comment by Go-Jaecheol** [comment]
* ## 최종 ERD

![image](https://user-images.githubusercontent.com/33208246/188276109-d36db2f0-5216-4a66-b27a-025335e6d9da.png)
